
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SeverityThreshold:
    Type: Number
    Default: 4
Resources:
  # SNSトピック
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: guardduty-finding-topic
  # SNSトピックポリシー
  EventTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "events.amazonaws.com"
            Action: "sns:Publish"
            Resource: "*"
      Topics:
        - !Ref SnsTopic
  # EventBridgeルール
  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties: 
      Name: guardduty-finding-event-rule
      EventPattern: !Sub |
        {
          "source": ["aws.guardduty"],
          "detail-type": ["GuardDuty Finding"],
          "detail": {
            "severity": [
              {"numeric": [">=", ${SeverityThreshold}]}
            ]
          }
        }
      Targets: 
        - Arn: !Ref SnsTopic
          Id: sns-topic